swagger: "2.0"
info:
  title: Todo Service
  description: Service for managing tasks
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /{id}:
    get:
      tags:
      - todo
      summary: get todo
      operationId: todo#get
      parameters:
      - name: id
        in: path
        description: Todo ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/TodoGetResponseBody'
      schemes:
      - http
  /openapi.json:
    get:
      summary: Download ./gen/http/openapi.json
      operationId: todo#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  TodoGetResponseBody:
    title: 'Mediatype identifier: todo; view=default'
    type: object
    properties:
      id:
        type: string
        description: Todo ID
        example: todo1
      task:
        type: string
        example: build an API
    description: GetResponseBody result type (default view)
    example:
      id: todo1
      task: build an API
    required:
    - id
    - task
